Iter20
trunov/go-shortener pull request #13
Opened 2023-10-13 10:12 UTC by trunov

2023-10-16 21:43 UTC, valentinsoe requested changes
Спасибо за работу!
Написал несколько комментариев. Из того, чего совсем не хватает - нет документации(описания) твоего multichecker.
И в задании явно указано не было, но также неплохо написать на него тесты.

2023-10-16 21:43 UTC, valentinsoe commented on cmd/shortener/main.go
> +//go:generate sh -c "printf %s $(git rev-parse HEAD) > commit.txt"
Это лишнее. У нас система сборки (github actions) знает на каком коммите она запускается.

2023-10-16 21:43 UTC, valentinsoe commented on cmd/shortener/main.go
> +var BuildCommit string
Эта(и остальные переменные) названы не по заданию.
С одной стороны - ничего страшного. С другой если у вас в компании стандартизованная система сборки, то переменным значение задано не будет.

2023-10-16 21:43 UTC, valentinsoe commented on cmd/shortener/main.go
> +	Version = util.DefaultIfEmpty(Version, "N/A")
Можно просто присвоить переменным пакета значения "N/A" в инициализаторе. При сборке их значения подменяться и не надо писать доп. функцию.

2023-10-16 21:43 UTC, valentinsoe commented on cmd/tools/tools.go
> +func runOsExit(pass *analysis.Pass) (interface{}, error) {
Занудство по именованию - run не самый удачный глагол на мой взгляд. Может check?

2023-10-16 21:43 UTC, valentinsoe commented on cmd/tools/tools.go
> +		if len(file.Comments) > 0 && strings.Contains(file.Comments[0].Text(), "Code generated by 'go test'. DO NOT EDIT.") {
На мой взгляд это избыточная проверка. Кажется автогенеренный код тоже можно проверить.

2023-10-16 21:43 UTC, valentinsoe commented on cmd/tools/tools.go
> +package main
Данный код лучше разместить в cmd/statclint.
А вот бинарный файл(собранный)  уже можно разместить в /tools

2023-10-19 13:15 UTC, trunov commented on cmd/tools/tools.go
> +		if len(file.Comments) > 0 && strings.Contains(file.Comments[0].Text(), "Code generated by 'go test'. DO NOT EDIT.") {
без него не проходило, это именно тест, там напрямую os.Exit вызов

2023-10-20 20:57 UTC, valentinsoe requested changes
Спасибо за исправления.
 Документации к статик-чекеру так и не появилось.

2023-10-24 08:20 UTC, valentinsoe approved these changes
Спасибо за исправления.
Работу принимаю

2023-10-24 08:20 UTC, valentinsoe commented on cmd/staticlint/testdata/pkg/pkg.go
> +package pkg
Тестов можно было написать и больше одного:)

2023-11-04 10:47 UTC, merged